repos:
  - repo: local
    hooks:
      - id: forbidden-files
        name: forbidden files
        entry: found copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
        exclude: ".copier-answers.yml"
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.265"
    hooks:
      - id: ruff
        exclude: "^docs/"
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black-jupyter
  - repo: https://github.com/kynan/nbstripout
    rev: "0.6.1"
    hooks:
      - id: nbstripout
